apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: su-oppgave
  namespace: default
  labels:
    team: supstonad
spec:
  image: {{ image }}
  replicas:
    min: 1
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /secret/supstonad/{{ secret_env }}
      - mountPath: /var/run/secrets/nais.io/srvuser
        kvPath: /serviceuser/data/{{ secret_env }}/srvsupstonad
  env:
     {{#each env}}
      - name: {{@key}}
        value: "{{this}}"
     {{/each}}